package com.practicum.list.core.theme

@Suppress("MagicNumber")
object ColorHex {
    const val PRIMARY_LIGHT_HEX = 0xFFD4C4B5
    const val ON_PRIMARY_LIGHT_HEX = 0xFFFFFFFF
    const val PRIMARY_CONTAINER_LIGHT_HEX = 0xFFFFDCBB
    const val ON_PRIMARY_CONTAINER_LIGHT_HEX = 0xFF2B1700
    const val SECONDARY_LIGHT_HEX = 0xFF845416
    const val SECONDARY_CONTAINER_LIGHT_HEX = 0xFFFEDDBD
    const val ON_SECONDARY_CONTAINER_LIGHT_HEX = 0xFF281805
    const val TERTIARY_CONTAINER_LIGHT_HEX = 0xFF845416
    const val ON_TERTIARY_CONTAINER_LIGHT_HEX = 0xFFFFFFFF
    const val SURFACE_LIGHT_HEX = 0xFFFFF8F4
    const val SURFACE_CONTAINER_LIGHT_HEX = 0xFFFAEBE0
    const val SURFACE_CONTAINER_HIGH_LIGHT_HEX = 0xFFF4E6DA
    const val SURFACE_CONTAINER_LOW_LIGHT_HEX = 0xFFFFF1E7
    const val SURFACE_CONTAINER_LOWEST_LIGHT_HEX = 0xFFFFFFFF
    const val ON_SURFACE_LIGHT_HEX = 0xFF211A14
    const val ON_SURFACE_VARIANT_LIGHT_HEX = 0xFF50453A
    const val INVERSE_ON_SURFACE_LIGHT_HEX = 0xFFFFF8F4
    const val OUTLINE_LIGHT_HEX = 0xFF827568
    const val OUTLINE_VARIANT_LIGHT_HEX = 0xFFD4C4B5
    const val SURFACE_CONTAINER_HIGHEST_LIGHT_HEX = 0xFFEEE0D5

    const val SURFACE_BRIGHT_LIGHT_HEX = 0xFF211A14
    const val PRIMARY_DARK_HEX = 0xFF19120C
    const val ON_PRIMARY_DARK_HEX = 0xFF241200
    const val PRIMARY_CONTAINER_DARK_HEX = 0xFFBE8543
    const val ON_PRIMARY_CONTAINER_DARK_HEX = 0xFF000000
    const val SECONDARY_DARK_HEX = 0xFFE5C5A7
    const val SECONDARY_CONTAINER_DARK_HEX = 0xFFA78C70
    const val ON_SECONDARY_CONTAINER_DARK_HEX = 0xFF000000
    const val TERTIARY_CONTAINER_DARK_HEX = 0xFFFFBE77
    const val ON_TERTIARY_CONTAINER_DARK_HEX = 0xFF241200
    const val SURFACE_DARK_HEX = 0xFF19120C
    const val SURFACE_CONTAINER_DARK_HEX = 0xFF251E17
    const val SURFACE_CONTAINER_HIGH_DARK_HEX = 0xFF302921
    const val SURFACE_CONTAINER_LOW_DARK_HEX = 0xFF211A14
    const val SURFACE_CONTAINER_LOWEST_DARK_HEX = 0xFF130D07
    const val ON_SURFACE_DARK_HEX = 0xFFFFFAF8
    const val ON_SURFACE_VARIANT_DARK_HEX = 0xFFD9C8B9
    const val INVERSE_ON_SURFACE_DARK_HEX = 0xFF302921
    const val OUTLINE_DARK_HEX = 0xFFB0A092
    const val OUTLINE_VARIANT_DARK_HEX = 0xFF8F8174
    const val SURFACE_CONTAINER_HIGHEST_DARK_HEX = 0xFF3B332C
    const val SURFACE_BRIGHT_DARK_HEX = 0xFFEEE0D5
}
