package com.practicum.list.core.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(ColorHex.PRIMARY_LIGHT_HEX)
val OnPrimaryLight = Color(ColorHex.ON_PRIMARY_LIGHT_HEX)
val PrimaryContainerLight = Color(ColorHex.PRIMARY_CONTAINER_LIGHT_HEX)
val OnPrimaryContainerLight = Color(ColorHex.ON_PRIMARY_CONTAINER_LIGHT_HEX)
val SecondaryLight = Color(ColorHex.SECONDARY_LIGHT_HEX)
val SecondaryContainerLight = Color(ColorHex.SECONDARY_CONTAINER_LIGHT_HEX)
val OnSecondaryContainerLight = Color(ColorHex.ON_SECONDARY_CONTAINER_LIGHT_HEX)
val TertiaryContainerLight = Color(ColorHex.TERTIARY_CONTAINER_LIGHT_HEX)
val OnTertiaryContainerLight = Color(ColorHex.ON_TERTIARY_CONTAINER_LIGHT_HEX)

val SurfaceLight = Color(ColorHex.SURFACE_LIGHT_HEX)
val SurfaceContainerLight = Color(ColorHex.SURFACE_CONTAINER_LIGHT_HEX)
val SurfaceContainerHighLight = Color(ColorHex.SURFACE_CONTAINER_HIGH_LIGHT_HEX)
val SurfaceContainerLowLight = Color(ColorHex.SURFACE_CONTAINER_LOW_LIGHT_HEX)
val SurfaceContainerLowestLight = Color(ColorHex.SURFACE_CONTAINER_LOWEST_LIGHT_HEX)
val OnSurfaceLight = Color(ColorHex.ON_SURFACE_LIGHT_HEX)
val OnSurfaceVariantLight = Color(ColorHex.ON_SURFACE_VARIANT_LIGHT_HEX)
val InverseOnSurfaceLight = Color(ColorHex.INVERSE_ON_SURFACE_LIGHT_HEX)
val OutlineLight = Color(ColorHex.OUTLINE_LIGHT_HEX)
val OutlineVariantLight = Color(ColorHex.OUTLINE_VARIANT_LIGHT_HEX)
val SurfaceContainerHighestLight = Color(ColorHex.SURFACE_CONTAINER_HIGHEST_LIGHT_HEX)

val PrimaryDark = Color(ColorHex.PRIMARY_DARK_HEX)
val OnPrimaryDark = Color(ColorHex.ON_PRIMARY_DARK_HEX)
val PrimaryContainerDark = Color(ColorHex.PRIMARY_CONTAINER_DARK_HEX)
val OnPrimaryContainerDark = Color(ColorHex.ON_PRIMARY_CONTAINER_DARK_HEX)
val SecondaryDark = Color(ColorHex.SECONDARY_DARK_HEX)
val SecondaryContainerDark = Color(ColorHex.SECONDARY_CONTAINER_DARK_HEX)
val OnSecondaryContainerDark = Color(ColorHex.ON_SECONDARY_CONTAINER_DARK_HEX)
val TertiaryContainerDark = Color(ColorHex.TERTIARY_CONTAINER_DARK_HEX)
val OnTertiaryContainerDark = Color(ColorHex.ON_TERTIARY_CONTAINER_DARK_HEX)

val SurfaceDark = Color(ColorHex.SURFACE_DARK_HEX)
val SurfaceContainerDark = Color(ColorHex.SURFACE_CONTAINER_DARK_HEX)
val SurfaceContainerHighDark = Color(ColorHex.SURFACE_CONTAINER_HIGH_DARK_HEX)
val SurfaceContainerLowDark = Color(ColorHex.SURFACE_CONTAINER_LOW_DARK_HEX)
val SurfaceContainerLowestDark = Color(ColorHex.SURFACE_CONTAINER_LOWEST_DARK_HEX)
val OnSurfaceDark = Color(ColorHex.ON_SURFACE_DARK_HEX)
val OnSurfaceVariantDark = Color(ColorHex.ON_SURFACE_VARIANT_DARK_HEX)
val InverseOnSurfaceDark = Color(ColorHex.INVERSE_ON_SURFACE_DARK_HEX)
val OutlineDark = Color(ColorHex.OUTLINE_DARK_HEX)
val OutlineVariantDark = Color(ColorHex.OUTLINE_VARIANT_DARK_HEX)
val SurfaceContainerHighestDark = Color(ColorHex.SURFACE_CONTAINER_HIGHEST_DARK_HEX)
